name: Python Script Workflow

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Python script
        run: python python.py

      - name: Make the directory
        run: mkdir -p /home/runner/work/MFE1/MFE1/internmediate

      - name: Checkout out intermediate repo
        uses: actions/checkout@v3
        with:
          repository: "mamoanwar97-procore/Intermediate"
          token: ${{ secrets.INTERMEDIATE_TOKEN }}
          path: internmediate

      - name: Copy the specific files
        run: |
          ls -a /home/runner/work/MFE1
          ls -a /home/runner/work/MFE1/internmediate
