name: Python Script Workflow

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Python script
        run: python python.py

      - name: Make the directory
        run: mkdir -p /home/runner/work/MFE1/MFE1/intermediate

      - name: Set up Git
        run: |
          git config --global user.name "mamoanwar97-procore"
          git config --global user.email "mahmoud.m.anwar@procore.com"

      - name: Checkout out intermediate repo
        uses: actions/checkout@v3
        with:
          repository: "mamoanwar97-procore/Intermediate"
          token: ${{ secrets.INTERMEDIATE_TOKEN }}
          path: intermediate

      - name: Commit updated translations to intermediate repo
        run: |
          ls -la /home/runner/work/MFE1
          ls -la /home/runner/work/MFE1/MFE1
          ls -la /home/runner/work/MFE1/MFE1/translations
          ls -la /home/runner/work/MFE1/MFE1/intermediate/intermediate
